import type { Metadata } from "next";
import "./globals.css";
import Header from "./_neutral/header/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-millik antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
