import { z } from "zod";

const featureSchema = z.object({
//   id: z.string(),
  name: z.string().default("Feature"),
//   icon: z.string(),
  hasAmpleParkingSpace: z.boolean().default(false),
  hasUniformSecurity: z.boolean().default(false),
  hasCCTVSurveillanceSystem: z.boolean().default(false),
  hasInverter: z.boolean().default(false),
  has24HoursElectricity: z.boolean().default(false),
  hasInternetServices: z.boolean().default(false),
  hasFiberOptics: z.boolean().default(false),
  hasReliableWaterSupply: z.boolean().default(false),
  hasChildernPlayground: z.boolean().default(false),
  hasEquestrainOrPoloCenter: z.boolean().default(false),
  hasTennisCourt: z.boolean().default(false),
  hasGolfCourt: z.boolean().default(false),
  hasLoungeOrBar: z.boolean().default(false),
  hasResturant: z.boolean().default(false),
  hasLakesOrPonds: z.boolean().default(false),
  hasGazebos: z.boolean().default(false),
  hasChildcareFacilities: z.boolean().default(false),
  hasSchool: z.boolean().default(false),
  hasHospital: z.boolean().default(false),
  hasShoppingComplex: z.boolean().default(false),
  hasChurchOrMosque: z.boolean().default(false),
  hasGreeneryAndOpenGardens: z.boolean().default(false),
  hasGym: z.boolean().default(false),
  hasBasketballCourt: z.boolean().default(false),
  hasFootballPitch: z.boolean().default(false),
  hasSwimmingPool: z.boolean().default(false),
  hasClubHouse: z.boolean().default(false),
  hasBank: z.boolean().default(false),
  hasCinema: z.boolean().default(false),
  hasEnsuite: z.boolean().default(false),
  hasPoPCeiling: z.boolean().default(false),
  hasWalkInClosets: z.boolean().default(false),
  hasAirConditioning: z.boolean().default(false),
  hasSpeedInternet: z.boolean().default(false),
  hasWineCeller: z.boolean().default(false),
  hasFurnished: z.boolean().default(false),
  hasWifi: z.boolean().default(false),
  hasFibreOptics: z.boolean().default(false),
  hasSatelliteTV: z.boolean().default(false),
  hasElevator: z.boolean().default(false),
  hasBoysQuarters: z.boolean().default(false),
  hasSmartHomeTechnology: z.boolean().default(false),
  hasFullyEquippedKitcken: z.boolean().default(false),
  hasModernAppliances: z.boolean().default(false),
  hasGraniteCountertops: z.boolean().default(false),
  hasBreakfastBar: z.boolean().default(false),
  hasStorageRoom: z.boolean().default(false),
  hasUpgradedBathroomFeatures: z.boolean().default(false),
  hasSpaLikeFeatures: z.boolean().default(false),
  hasTileOrMarbleFeatures: z.boolean().default(false),
  hasOpenFloorPlan: z.boolean().default(false),
  hasLargeWindwos: z.boolean().default(false),
  hasBuiltInHouseTheater: z.boolean().default(false),
  hasPrivateBackyard: z.boolean().default(false),
  hasPatioOrDarkSpace: z.boolean().default(false),
  hasLandscapedGarden: z.boolean().default(false),
  hasHomeOfficeSpace: z.boolean().default(false),
  hasBuiltInShelfOrBookSpace: z.boolean().default(false),
  hasAmpleNaturalLight: z.boolean().default(false),
  hasSecuritySystem: z.boolean().default(false),
  hasBulletProofDoors: z.boolean().default(false),
  hasGatedCompound: z.boolean().default(false),
  hasReinforcedDoorsAndWindows: z.boolean().default(false),
  hasGaurdedCommunity: z.boolean().default(false),
  hasUniformedSecurity: z.boolean().default(false),
  hasParkingGarage: z.boolean().default(false),
  hasDriveWaySpace: z.boolean().default(false),
  hasStreetParkingAvaliability: z.boolean().default(false),
  hasPrivateParkingSpace: z.boolean().default(false),
  hasElectricity: z.boolean().default(false),
  hasBackupGenerator: z.boolean().default(false),
  hasBorehole: z.boolean().default(false),
  hasWaterBoard: z.boolean().default(false),
  hasProximityToSchools: z.boolean().default(false),
  hasProximityToShoppingMalls: z.boolean().default(false),
  hasProximityToSupermarkets: z.boolean().default(false),
  hasNearByPublicTransportation: z.boolean().default(false),
  hasAccessiblityViaBoltOrUber: z.boolean().default(false),
  hasFencedBackyard: z.boolean().default(false),
  hasPetFriendlyNeighbourhood: z.boolean().default(false),
  hasNearbyWalkingTrailsAndSidewalks: z.boolean().default(false),
});

// Define the main schema
export const estateZSchema = z.object({
  name: z.string(),
  cityId: z.string(),
  address: z.string(),
  videoUrl: z.string().url(),
  ownerType: z.string(),
  landmark: z.string(),
  description: z.string(),
  completionStatus: z.string(),
  completionDate: z.string().datetime(),
  completionLevel: z.number().int().min(0), 
  longitude: z.number(),
  latitude: z.number(),
  features: z.array(featureSchema), 
  landSize: z.number().min(0), 
  organizationId: z.string(),
  floors: z.number().int().min(0),
});

export type estateZType = z.infer<typeof estateZSchema>;
